SMSUI/ViewModels/Staff/TeacherBatchViewModel.cs
using SMSUI.ViewModels.SchoolSetting;
﻿using System.Collections.Generic;
using SMSUI.ViewModels.Exam;
using SMSUI.ViewModels.SchoolSetting;
using SMSUI.ViewModels.Teacher;

namespace SMSUI.ViewModels.Staff
{
    public class TeacherBatchViewModel
    {
        public TeacherBatchViewModel()
        {
            TeacherTerm = new TeacherTermViewModel();
            Subject = new SubjectViewModel();
            TeacherBatchExamViewModels = new List<TeacherBatchExamViewModel>();
        }
        public int TeacherBatchID { get; set; }
        public TeacherTermViewModel TeacherTerm { get; set; }
        public SubjectViewModel Subject { get; set; }

        public GradeLevelViewModel GradeLevelViewModel
        {
            get {
                return TeacherTerm.Class.GradeLevelViewModel;
            }
        }
        public List<TeacherBatchExamViewModel> TeacherBatchExamViewModels { get; set; }

        public string ClassNameWithSubject { get { return TeacherTerm.Class.Name + " - " + Subject; } }
    }

}

SMSUI/ViewModels/Staff/TeacherViewModel.cs
using System.ComponentModel;

namespace SMSUI.ViewModels.Staff
{
    public class TeacherViewModel
    {
        public int TeacherID { get; set; }

        [DisplayName("ID #")]
        public string IdNumber { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }
       
        public bool IsActive { get; set; }
        public string Photo { get; set; }
        public AddressViewModel Address { get; set; }
        public DemographicInfoViewModel DemographicInformation { get; set; }

        public string FullName
        {
            get
            {
                var title = DemographicInformation.Sex == "Male" ? "Mr." : "Mrs.";
                return title + " " + FirstName + " " + MiddleName;
            }
        }
    }
}

SMSUI/ViewModels/Teacher/ClassWithSubjectViewModel.cs
using System.Collections.Generic;
using System.Linq;
using SMSUI.ViewModels.Exam;
using SMSUI.ViewModels.SchoolSetting;

namespace SMSUI.ViewModels.Teacher
{
    public class ClassWithSubjectViewModel
    {
        public List<TeacherBatchExamViewModel> TeacherBatchExamViewModels { get; set; }

        public List<SubjectViewModel> SubjectViewModels
        {
            get
            {
                return TeacherBatchExamViewModels.Select(s => s.TeacherBatch.Subject).Distinct().ToList();
            }
        }

        public List<ClassViewModel> ClassViewModels
        {
            get
            {
                return TeacherBatchExamViewModels.Select(t => t.TeacherBatch.TeacherTerm.Class).Distinct().ToList();
            }
        }

        public List<string> ClassWithSubjectsAggrigated { get; set; } //~Fake One There is no such list ~//
    }
}

SMSUI/ViewModels/Teacher/ExamResultViewModel.cs
using System;
using SMSUI.ViewModels.Exam;

namespace SMSUI.ViewModels.Teacher
{
    public class ExamResultViewModel
    {
        public int ExamResultID { get; set; }
        public ExamViewModel Exam { get { return TeacherBatchExamViewModel.Exam; } }
        public StudentBathViewModel StudentBathViewModel { get; set; }
        public TeacherBatchExamViewModel   TeacherBatchExamViewModel { get; set; }
        public double Point { get; set; }
        public DateTime DateOfEntry { get; set; }
        public string ScoredOutOf { get { return Point + "/" + Exam.Mark; } }
    }
}

SMSUI/ViewModels/Teacher/GradeReport/ClassResultStatusViewModel.cs
using System;
using SMSUI.ViewModels.Staff;

namespace SMSUI.ViewModels.Teacher.GradeReport
{
    public class ClassResultStatusViewModel
    {
        public int ClassResultStatusID { get; set; }
        public TeacherBatchViewModel  TeacherBatchViewModel { get; set; }
        public DateTime SubmittedDate { get; set; }
        public bool IsConfirmed { get; set; }
        public DateTime ConfirmationDate { get; set; }
    }
}

SMSUI/ViewModels/Teacher/GradeReport/GradeReportPageViewModel.cs
using System.Collections.Generic;
using SMSUI.ViewModels.SchoolSetting;

namespace SMSUI.ViewModels.Teacher.GradeReport
{
    public class GradeReportPageViewModel
    {
        public ClassViewModel ClassViewModel { get; set; }
        public TermViewModel TermViewModel { get; set; }
        public SchoolInformationViewModel SchoolInformationViewModel { get; set; }
        public IList<GradeReportViewModel> GradeReportViewModels { get; set; }

    }
}

SMSUI/ViewModels/Teacher/GradeReport/GradeReportViewModel.cs
namespace SMSUI.ViewModels.Teacher.GradeReport
{
    public class GradeReportViewModel
    {
        public StudentBathViewModel StudentBatchViewModel { get; set; }
        public int Biology { get; set; }
        public int Chemistry { get; set; }
        public int Maths { get; set; }
        public double Total { get; set; }
        public int Rank { get; set; }
        public string Absence { get; set; }

    }
}

SMSUI/ViewModels/Teacher/GradeReport/StudentExamResultViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using SMSUI.ViewModels.Exam;
using SMSUI.ViewModels.SchoolSetting;
using SMSUI.ViewModels.Staff;

namespace SMSUI.ViewModels.Teacher.GradeReport
{
    public class StudentExamResultViewModel
    {
        public StudentBathViewModel StudentBatchViewModel { get; set; }
        public TeacherBatchViewModel TeacherBatchViewModel { get; set; }

        [DisplayName("Student")]
        public string StudentFullName
        {
            get
            {
                return StudentBatchViewModel.StudentViewModel.StudentFullName;
            }
        }

        public string StudentIDNumber
        {
            get
            {
                return StudentBatchViewModel.StudentViewModel.IdNumber;
            }
        }

        public IList<ExamViewModel> ExamsTaken { get; set; }

        public string TeacherFullName
        {
            get
            {
                return TeacherBatchViewModel.TeacherTerm.Teacher.FullName;
            }
        }

        public double Mark { get; set; }
        public List<ExamResultViewModel> ExamResults { get; set; } 

        public SubjectViewModel SubjectViewModel
        {
            get
            {
                return TeacherBatchViewModel.Subject;
            }
        }

        public ClassViewModel ClassViewModel
        {
            get
            {
                return TeacherBatchViewModel.TeacherTerm.Class;
            }
        }
        public double Total { get { return ExamResults.Sum(p => p.Point); } }
    }
}

SMSUI/ViewModels/Teacher/GradeReport/StudentGradeReportPageViewModel.cs
using SMSUI.ViewModels.SchoolSetting;

namespace SMSUI.ViewModels.Teacher.GradeReport
{
    public class StudentGradeReportPageViewModel
    {
        public StudentGradeReportPageViewModel()
        {
            StudentGradeReportViewModel = new StudentGradeReportViewModel();
        }

        public SchoolInformationViewModel School { get; set; }
        public string Class { get; set; }
        public string Year { get; set; }

        public StudentGradeReportViewModel StudentGradeReportViewModel { get; private set; }
    }
}

SMSUI/ViewModels/Teacher/GradeReport/StudentGradeReportViewModel.cs
namespace SMSUI.ViewModels.Teacher.GradeReport
{
    public class StudentGradeReportViewModel
    {

        public int StudentID { get; set; }
        public string Student { get; set; }
        public string IDNumber { get; set; }
        public int Biology { get; set; }
        public int Chemistry { get; set; }
        public int Maths { get; set; }
        public double Total { get; set; }
        public int Rank { get; set; }
    }
}

SMSUI/ViewModels/Teacher/MyStudentsViewModel.cs
using System.Collections.Generic;

namespace SMSUI.ViewModels.Teacher
{
    public class MyStudentsViewModel
    {
        public StudentsExamInfoViewModel StudentsExamInfoViewModel { get; set; }
        public List<ExamResultViewModel> ExamResultViewModels { get; set; }
        public StudentExamResultInformationViewModel StudentExamResultInformationViewModel { get; set; }
    }
}

SMSUI/ViewModels/Teacher/StudentBathViewModel.cs
using SMSUI.ViewModels.SchoolSetting;

namespace SMSUI.ViewModels.Teacher
{
    public class StudentBathViewModel
    {
        public StudentBathViewModel()
        {
            StudentViewModel = new StudentViewModel();
            TermViewModel = new TermViewModel();
            ClassViewModel = new ClassViewModel();
        }
        public int StudentBatchID  { get; set; }
        public int StudentID { get { return StudentViewModel.StudentId; } }
        public StudentViewModel StudentViewModel { get; set; }
        public TermViewModel TermViewModel { get; set; }
        public ClassViewModel ClassViewModel { get; set; }

    }
}

SMSUI/ViewModels/Teacher/StudentExamResultInformationViewModel.cs
using System.Collections.Generic;
using System.Linq;
using SMSUI.ViewModels.Exam;
using SMSUI.ViewModels.Teacher.GradeReport;

namespace SMSUI.ViewModels.Teacher
{
    public class StudentExamResultInformationViewModel
    {
        public List<ClassWithSubjectViewModel> ClassWithSubjectAggrigatedViewModel { get; set; }
        public List<ExamViewModel> ExamsTakenWithnAclass { get; set; } //~ Fake One!~//

        public List<StudentExamResultViewModel> StudentExamResults { get; set; }

        //public List<IEnumerable<ExamViewModel>> ExamsTakenWithnAclass
        //{
        //    get
        //    {
        //        return
        //            ClassWithSubjectAggrigatedViewModel.Select(
        //                t => t.TeacherBatchExamViewModels.ToList().Select(e => e.Exam))
        //                .Distinct()
        //                .ToList();
        //    }
        //}


    }
}

SMSUI/ViewModels/Teacher/StudentResultViewModel.cs
using System.ComponentModel;
using SMSUI.ViewModels.SchoolSetting;
using SMSUI.ViewModels.Staff;

namespace SMSUI.ViewModels.Teacher
{
    public class StudentResultViewModel
    {
        public int StudentResultID { get; set; }
        public TeacherViewModel Teacher
        {
            get; set;
        }
        public ClassViewModel Class
        {
            get; set;

        }
        public SubjectViewModel Subject
        {
            get; set;
        }
        [DisplayName("Confirmed")]
        public bool IsConfirmed { get; set; }

        public string SubmissionDate { get; set; }
        public string ConfirmationDate { get; set; }

       

    }
}

SMSUI/ViewModels/Teacher/StudentsExamInfoViewModel.cs
using System.Collections.Generic;
using System.Linq;
using SMSUI.ViewModels.Exam;
using SMSUI.ViewModels.SchoolSetting;
using SMSUI.ViewModels.Staff;

namespace SMSUI.ViewModels.Teacher
{
    public class StudentsExamInfoViewModel
    {
        public StudentsExamInfoViewModel()
        {
            _teacherBatchExamViewModels = new List<TeacherBatchExamViewModel>();
            TeacherBatchViewModels = new List<TeacherBatchViewModel>();
        }

        public List<ClassViewModel> ClassViewModels
        {
            get
            {
                return TeacherBatchViewModels.Select(c => c.TeacherTerm.Class).Distinct().ToList();
            }
        }
        public List<SubjectViewModel> SubjectViewModels
        {
            get
            {
                return TeacherBatchViewModels.Select(c => c.Subject).Distinct().ToList();
            }
        }

        public List<StudentBathViewModel> StudentBathViewModels { get; set; }
        public List<TeacherBatchViewModel> TeacherBatchViewModels { get; set; }


        private List<TeacherBatchExamViewModel> _teacherBatchExamViewModels { get; set; }
        public List<TeacherBatchExamViewModel> TeacherBatchExamViewModels
        {
            get
            {
                if (_teacherBatchExamViewModels.Count > 0) return _teacherBatchExamViewModels;
                foreach (var teacherBatchViewModel in TeacherBatchViewModels)
                {
                    _teacherBatchExamViewModels.AddRange(teacherBatchViewModel.TeacherBatchExamViewModels);
                }
                return _teacherBatchExamViewModels;
            }
        }



        public double Point { get; set; }
        public ClassViewModel ClassViewModel { get; set; }
        public StudentBathViewModel StudentBathViewModel { get; set; }
        public TeacherBatchViewModel TeacherBatchViewModel { get; set; }
        public TeacherBatchExamViewModel TeacherBatchExamViewModel { get; set; }
    }
}

SMSUI/Controllers/ModalsController.cs
using System.Web.Mvc;
using SMSUI.Repository;
using SMSUI.ViewModels;
using SMSUI.ViewModels.SchoolSetting;

namespace SMSUI.Controllers
{
    public class ModalsController : Controller
    {
        public FakeSchoolService SchoolService = new FakeSchoolService();
        //
        // GET: /Modal/

        public ActionResult _AddressModal(int? addressID)
        {
            var addressInformation = SchoolService.GetAddressInformationViewModel(addressID);
            return PartialView(addressInformation);
        }

        [HttpPost]
        public void SaveAddress(AddressViewModel addressViewModel)
        {
            //~ save changes on addressViewModel to SMS DB ~//
            //return Json(new { success = true, url = Url.Action("_AddressPlugin", "School"), requestFromAddressModal = true });
        }

        public ActionResult _AcademicYearModal(int? academicYearID)
        {
            var academicYear = SchoolService.GetAcademicYearViewModel(academicYearID);
            return PartialView(academicYear);
        }

        [HttpPost]
        public void SaveAcademicYear(AcademicYearViewModel academicYearViewModel)
        {
            //Save Academic year
        }

        public ActionResult _TermModal(int? termID)
        {
            var academicYear = SchoolService.GetTermViewModel(termID);
            return PartialView(academicYear);
        }

        [HttpPost]
        public void SaveTerm(TermViewModel termViewModel)
        {
            //Save Term
        }

        public ActionResult _GradeLevelModal(int? gradeLevelID)
        {
            var gradeLevel = SchoolService.GetGradeLevelViewModel(gradeLevelID);
            return PartialView(gradeLevel);
        }

        [HttpPost]
        public void SaveGradeLevel(GradeLevelViewModel gradeLevelViewModel)
        {
            //Save Term
        }

        public ActionResult _SubjectModal(int? subjectID)
        {
            var subject = SchoolService.GetSubjectInfoViewModel(subjectID);
            return PartialView(subject);
        }

        [HttpPost]
        public void SaveSubject(SubjectViewModel subjectViewModel)
        {
            //Save Term
        }
    }
}

SMSUI/Controllers/TeacherController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SMSUI.Repository;
using SMSUI.ViewModels.Staff;

namespace SMSUI.Controllers
{
    public class TeacherController : Controller
    {
        //
        // GET: /Teacher/
        private readonly FakeTeacherService _teacherService = new FakeTeacherService();
        private  readonly FakeAccountService _accountService = new FakeAccountService();
        private IEnumerable<TeacherViewModel> _teachers = new List<TeacherViewModel>(); 
        public ActionResult Index()
        {

            _teachers = _teacherService.GetAllTeachers().ToList();         
            ViewBag.loggedinUser = _accountService.GetLoggedInUsertemp();
            return View(_teachers);
        }

        public ActionResult _TeacherBatch()
        {
            _teachers = _teacherService.GetAllTeachers();
            ViewBag.loggedinUser = _accountService.GetLoggedInUsertemp();
            return View(_teachers);
        }

        public ActionResult _UpdateTeacherBatch( int teacherId)
        {
            ViewBag.loggedinUser = _accountService.GetLoggedInUsertemp();
            var teacherBatch = _teacherService.GeTeacherBatchByTeacherID(teacherId);
            var service = new FakeSchoolService();

            var page = new TeacherBatchPageViewModel
            {
                TeacherBatchViewModels = teacherBatch,
               };


            return View(page);
        }

        [HttpPost]
        public ActionResult _UpdateTeacherBatch(TeacherBatchViewModel teacherBatch)
        {
            var term = new FakeSchoolService().GetTermViewModel(1);//Assuming this is the current term

            ViewBag.loggedinUser = _accountService.GetLoggedInUsertemp();
          return  RedirectToAction("_teacherbatch");
        }


        public ActionResult _Teacher(int? teacherID)
        {
            ViewBag.loggedinUser = _accountService.GetLoggedInUsertemp();
            var teacher = _teacherService.GetTeacherByID(teacherID);
            return View(teacher);

        }

        [HttpPost]
        public ActionResult _Teacher(TeacherViewModel teacherViewModel)
        {
            ViewBag.loggedinUser = _accountService.GetLoggedInUsertemp();
            var model = new TeacherViewModel
            {
                FirstName = teacherViewModel.FirstName,
                MiddleName = teacherViewModel.MiddleName,
                LastName = teacherViewModel.LastName,
                IdNumber = teacherViewModel.IdNumber,
                TeacherID = 100,
                IsActive = true,
                Address = teacherViewModel.Address ?? FakeService.GetAddress(),
                DemographicInformation = teacherViewModel.DemographicInformation??FakeService.GetDemographicInformationUser()
            };
            return View("_Teacher",model);
        }
    }
}

SMSUI/Views/Teacher/Index.cshtml
@using SMSUI.Helpers
@using SMSUI.ViewModels.Staff
@model IEnumerable<SMSUI.ViewModels.Staff.TeacherViewModel>

@{
    Layout = ("~/Views/Shared/_LoggedInLayout.cshtml");
}
<section id="main-content">
<section class="wrapper">
    <div class="wizard-container">
        <div class="card wizard-card ct-wizard-orange" id="" style="min-height: 600px;">
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <div>
                            <div class="panel-body">
                                <span class="glyphicon glyphicon-plus-sign"></span>
                                @Html.ActionLink("Add Teacher", "_teacher", "Teacher") <!--use fa-plus icon-->

                            </div>

                            <table class="table table-striped table-hover" id="teachersTable" style="margin-top: 100px;">
                                <thead>
                                    <tr>
                                        <th class="hidden-phone"><i class="fa fa-question-circle"></i> @Html.DisplayNameFor(model => model.IdNumber)</th>
                                        <th><i class="fa fa-bullhorn"></i> @Html.DisplayNameFor(model => model.FirstName)</th>
                                        <th class="hidden-phone"><i class="fa fa-question-circle"></i> @Html.DisplayNameFor(model => model.MiddleName)</th>
                                        <th class="hidden-phone"><i class="fa fa-question-circle"></i> @Html.DisplayNameFor(model => model.LastName)</th>
                                        <th class="hidden-phone" title="Status"><i class="fa fa-edit"></i> @Html.DisplayNameFor(model => model.IsActive) </th>
                                        <th class="hidden-phone" title="Action"><i class="fa fa-edit"></i> Action </th>
                                    </tr>
                                </thead>
                                <tbody class="searchable">
                                    @foreach (TeacherViewModel tvm in Model)
                                    {
                                        <tr>
                                            <td>@tvm.IdNumber</td>
                                            <td>@tvm.FirstName</td>
                                            <td>@tvm.MiddleName</td>
                                            <td>@tvm.LastName</td>
                                            <td>
                                                @if (@tvm.IsActive)
                                                { <button class="btn btn-success btn-xs" disabled="disabled"><i class="fa fa-check"></i></button>}
                                                else
                                                {<button class="btn btn-danger btn-xs" disabled="disabled"><i class="fa li_lock "></i></button>}

                                            </td>
                                            <td>
                                                @Html.NoEncodeActionLink("<span class='btn btn-primary btn-xs'><i class='fa fa-pencil'></i></span>", "_Teacher", "_Teacher", "Teacher", routeValues: new { @teacherId = tvm.TeacherID })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
</section>
    </section>


<script src="~/Content/js/jquery.js"></script>
<script type="text/javascript">
    $(function () {
        $("#teachersTable").dataTable();
    });
</script>

SMSUI/Views/Teacher/_Teacher.cshtml
@using System.Web.Mvc.Html
@using SMSUI.ViewModels
@model SMSUI.ViewModels.Staff.TeacherViewModel
@{
    Layout = ("~/Views/Shared/_LoggedInLayout.cshtml");
}
@using (Html.BeginForm("_teacher", "Teacher", FormMethod.Post))
{
    <section id="main-content">
    <section class="wrapper">
        <div class="wizard-container">
            <div class="card wizard-card ct-wizard-orange" id="" style="min-height: 550px;">
                    
                    <div class="col-lg-12">

                        <div class="col-lg-5" style="margin-top: 10px">
                            <span style="font-size: 24px; font-family: 'Calibri Light';">Teacher Info:</span>
                            <div class="form-panel" style="height: 200px; align-self: center">
                                <div class="row col-md-12">
                                    <div class="col-md-5">
                                        @Html.LabelFor(model => model.IdNumber, "ID Number", new {@style = "font-size: 20px; font-family: 'Calibri Light';text-align: left;"})
                                    </div>
                                    <div class="col-md-7">
                                        @Html.TextBoxFor(model => model.IdNumber, new {@class = "form-control", @id = "txtTeacherIdNumber", @autofocus = "true", @style = "font-size: 20px; font-family: 'Calibri Light';width: 160px;text-align: center; height: 30px"})
                                    </div>
                                </div>
                                <div class="row col-md-12" style="">
                                    <div class="col-md-5">
                                        @Html.LabelFor(model => model.FirstName, "First Name", new {@style = "font-size: 20px; font-family: 'Calibri Light';text-align: left;"})
                                    </div>
                                    <div class="col-md-7">
                                        @Html.TextBoxFor(model => model.FirstName, new {@class = "form-control", @id = "txtTeacherFirstName", @autofocus = "true", @style = "font-size: 20px; font-family: 'Calibri Light';width: 160px;text-align: center; height: 30px"})
                                    </div>
                                </div>
                                <div class="row col-md-12">
                                    <div class="col-md-5">
                                        @Html.LabelFor(model => model.MiddleName, "Middle Name", new {@style = "font-size: 20px; font-family: 'Calibri Light';text-align: left;"})
                                    </div>
                                    <div class="col-md-7">
                                        @Html.TextBoxFor(model => model.MiddleName, new {@class = "form-control", @id = "txtTeacherMiddleName", @autofocus = "true", @style = "font-size: 20px; font-family: 'Calibri Light';width: 160px;text-align: center; height: 30px"})
                                    </div>
                                </div>
                                <div class="row col-md-12">
                                    <div class="col-md-5">
                                        @Html.LabelFor(model => model.LastName, "Last Name", new {@style = "font-size: 20px; font-family: 'Calibri Light';text-align: left;"})
                                    </div>
                                    <div class="col-md-7">
                                        @Html.TextBoxFor(model => model.LastName, new {@class = "form-control", @id = "txtTeacherLastName", @autofocus = "true", @style = "font-size: 20px; font-family: 'Calibri Light';width: 160px;text-align: center; height: 30px"})
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-2" style="margin-top: 50px">
                            <div class="picture-container">
                                <div class="picture" style="height: 106px; width: 106px; -ms-border-radius: 50%; border-radius: 50%">
                                    <img src="~/Content/img/default-avatar.png" class="picture-src" id="wizardPicturePreview" title="" />
                                    <input type="file" id="wizard-picture">
                                </div>
                            </div>

                            <span style="font-size: 24px; font-family: 'Calibri Light';">Attach Photo</span>
                        </div>
                    </div>
                    <hr />
                    <div class="col-lg-12">
                        @{
                            Html.RenderPartial("_AddressPlugin", new List<AddressViewModel> {@Model.Address});
                                
                            <a href=@Url.Action("_AddressModal","Modals") class="open-form-modal"><i class="li_tag"></i> Add Address</a>
                        }
                    </div>
                    <hr />
                    <div class="col-lg-12">
                        @{
                            Html.RenderPartial("_DemographicInfo", @Model.DemographicInformation);
                            <a href=@Url.Action("DemographicInfoModal", "Home") class="open-form-modal"><i class="li_tag"></i> Add New</a>
                        }
                    </div>
                    <hr />
                    
                    <div class="saveTeacher pull-right" style="padding-right: 30px; padding-top: 10px">
                       
                        
                        <input class="btn btn-info btn-success" style="background: #424a5d; color: #77ff7e; " type="submit" value="Save" />
                        <a href="@Url.Action("Index", "Teacher")" style="background: #424a5d; color: #ffd777; " class="btn btn-app"><i class="glyphicon glyphicon-arrow-left"></i> Back</a>
                        
                    </div>
                </div>

                   
                
            </div>
        
        </section>
    </section>
}

SMSUI/Views/Teacher/_TeacherBatch.cshtml
@using SMSUI.Helpers
@using SMSUI.ViewModels.Staff
@model IEnumerable<SMSUI.ViewModels.Staff.TeacherViewModel>

@{
    Layout = ("~/Views/Shared/_LoggedInLayout.cshtml");
}

<section id="main-content">
    <section class="wrapper">

        <div class="wizard-container">
            <div class="card wizard-card ct-wizard-orange" id="" style="min-height: 550px;">

                <div class="row mt">
                    <div class="col-md-12">
                        <div class="content-panel">
                            <div>
                                <table class="table table-striped table-hover" id="teachersTable" style="margin-top: 100px;">
                                    <thead>
                                        <tr>
                                            <th class="hidden-phone"><i class="fa fa-question-circle"></i> @Html.DisplayNameFor(model => model.IdNumber)</th>
                                            <th><i class="fa fa-bullhorn"></i> @Html.DisplayNameFor(model => model.FirstName)</th>
                                            <th class="hidden-phone"><i class="fa fa-question-circle"></i> @Html.DisplayNameFor(model => model.MiddleName)</th>
                                            <th class="hidden-phone"><i class="fa fa-question-circle"></i> @Html.DisplayNameFor(model => model.LastName)</th>
                                            <th class="hidden-phone" title="Status"><i class="fa fa-edit"></i> @Html.DisplayNameFor(model => model.IsActive) </th>
                                            <th class="hidden-phone" title="Action"><i class="fa fa-edit"></i> Action </th>
                                        </tr>
                                    </thead>
                                    <tbody class="searchable">
                                        @foreach (TeacherViewModel tvm in Model)
                                        {
                                            <tr>
                                                <td>@tvm.IdNumber</td>
                                                <td>@tvm.FirstName</td>
                                                <td>@tvm.MiddleName</td>
                                                <td>@tvm.LastName</td>
                                                <td>
                                                    @if (@tvm.IsActive)
                                                    { <button class="btn btn-success btn-xs" disabled="disabled"><i class="fa fa-check"></i></button>}
                                                    else
                                                    {<button class="btn btn-danger btn-xs" disabled="disabled"><i class="fa li_lock "></i></button>}

                                                </td>
                                                <td>
                                                    @Html.NoEncodeActionLink("<span class='btn btn-primary btn-xs'><i class='fa fa-pencil'></i></span>", "_UpdateTeacherBatch", "_UpdateTeacherBatch", "Teacher", routeValues: new { @teacherId = tvm.TeacherID })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
    </section>
</section>


<script src="~/Content/js/jquery.js"></script>
<script type="text/javascript">
    $(function () {
        $("#teachersTable").dataTable();
    });
</script>