SMSUI/ViewModels/Announcement/AnnouncementViewModel.cs
using System;
using System.Linq;
using System.Web;

namespace SMSUI.ViewModels.Announcement
{
    public class AnnouncementViewModel
    {
        public int AnnouncementID { get; set; }
        public string To { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public DateTime Date { get; set; }
        public string AttachmentUrl { get; set; }
        public bool IsSeen { get; set; }
    }
}

SMSUI/ViewModels/Announcement/ComposeMailViewModel.cs
using System.Collections.Generic;

namespace SMSUI.ViewModels.Announcement
{
    public class ComposeMailViewModel
    {
        public ComposeMailViewModel()
        {
            RoleViewModels = new List<RoleViewModel>();
            UserViewModels = new List<UserViewModel>();
        }

        public List<RoleViewModel> RoleViewModels { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public List<UserViewModel> UserViewModels { get; set; }
    }
}

SMSUI/ViewModels/Announcement/IntranetAnnouncementInformationViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace SMSUI.ViewModels.Announcement
{
    public class IntranetAnnouncementInformationViewModel
    {
        public int UserID { get; set; }
        public int InBoxMails { get { return Announcements.Count(m => m.IsSeen == false); }}
        public List<AnnouncementViewModel> Announcements { get; set; }
    }
}

SMSUI/ViewModels/Announcement/MailDetailViewModel.cs
namespace SMSUI.ViewModels.Announcement
{
    public class MailDetailViewModel
    {
        public AnnouncementViewModel AnnouncementViewModel { get; set; }
        public int InBoxMails { get; set; }
        public string FakeSetting { get; set; }
    }
}

SMSUI/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using SMSUI.Repository;
using SMSUI.ViewModels;
using SMSUI.ViewModels.Announcement;

namespace SMSUI.Controllers
{
    public class AnnouncementController : Controller
    {
        public FakeAccountService AccountService = new FakeAccountService();
        public FakeAnnouncementService AnnouncementService = new FakeAnnouncementService();
        private IntranetAnnouncementInformationViewModel _intranetAnnouncement;
        public ActionResult Index()
        {
            ViewBag.loggedinUser = AccountService.GetLoggedInUsertemp();
            _intranetAnnouncement = AnnouncementService.GetIntranetAnnoucementInfo();
            return View(_intranetAnnouncement);
        }

        //
        // GET: /Announcement/Details/5

        public ActionResult MailDetail(int? userAnnouncementID,string context)
        {
            ViewBag.loggedinUser = AccountService.GetLoggedInUsertemp();
            switch (context)
            {
                case "Inbox":
                    {
                        var mailDetailViewModel = GetFakeCachedMailDetail(userAnnouncementID);
                        return View(mailDetailViewModel);
                    }

                case "Sent":
                {
                    var mailDetailViewModel = GetFakeCachedSentMailDetail(userAnnouncementID);
                    return View(mailDetailViewModel);
                    }
            }
            //~ If We go this far sms is in danger! ;) ~//
            return View();
        }

        private MailDetailViewModel GetFakeCachedMailDetail(int? userAnnouncementID)
        {
            _intranetAnnouncement = AnnouncementService.GetIntranetAnnoucementInfo();
            return new MailDetailViewModel
            {
                AnnouncementViewModel =
                    _intranetAnnouncement.Announcements.FirstOrDefault(id => id.AnnouncementID == userAnnouncementID),
                FakeSetting = "Inbox",
                InBoxMails = _intranetAnnouncement.InBoxMails
            };
        }
        private MailDetailViewModel GetFakeCachedSentMailDetail(int? userAnnouncementID)
        {
            _intranetAnnouncement = AnnouncementService.GetIntranetAnnoucementInfo();
            var sentAnnouncement = AnnouncementService.GetIntranetSentAnnoucementInfo();
            return new MailDetailViewModel
            {
                AnnouncementViewModel =
                    sentAnnouncement.FirstOrDefault(id => id.AnnouncementID == userAnnouncementID),
                FakeSetting = "Sent",
                InBoxMails = _intranetAnnouncement.InBoxMails
            };
        }
        public ActionResult _Mail(string folderType)
        {
            switch (folderType)
            {
                case "Inbox":
                {
                    var announcements = AnnouncementService.GetIntranetAnnoucementInfo().Announcements;
                    return View(announcements);
                }

                case "Sent":
                {
                    var sentAnnouncement = AnnouncementService.GetIntranetSentAnnoucementInfo();
                    return View(sentAnnouncement);
                }
            }
            //~ If We go this far sms is in danger! ;) ~//
            return View();
        }
        //
        // GET: /Announcement/Create

        public ActionResult ComposeMail()
        {
            ViewBag.loggedinUser = AccountService.GetLoggedInUsertemp();
            var composeMailModel = AnnouncementService.GetComposeMailInfo();
            return View(composeMailModel);
        }

        public JsonResult GetRandomUsers(int[] filter)
        {
            List<UserViewModel> users = filter != null
                ? AnnouncementService.GetSampleUsers().Where(id => id.RoleID == filter[0]).ToList()
                : AnnouncementService.GetSampleUsers();
            return Json(users);
        }

        //
        // POST: /Announcement/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Announcement/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Announcement/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Announcement/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Announcement/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SMSUI/Views/Announcement/ComposeMail.cshtml
@model SMSUI.ViewModels.Announcement.ComposeMailViewModel
@{
    Layout = ("~/Views/Shared/_LoggedInLayout.cshtml");
}
<body>
    <section id="main-content">
        <section class="wrapper">
            <div class="wizard-card" style="min-height: 750px; padding-left: 30px;padding-right: 20px">
                
                <!--FILTER AREA-->
                <div class="col-lg-12">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-10 form-panel" style="border-style:none; padding-bottom: 50px;height: 60px">
                        <div class="form-group">
                            <label class="control-label" for="lkQuickEmailGroups">To : </label>
                            <select id="lkQuickEmailGroups" data-placeholder="Select Student" multiple="" class="chosen-select" style="width: 700px; height: 30px; ">
                                @foreach (var role in Model.RoleViewModels)
                                {
                                    <option value="@role.RoleID">@role.Name</option>
                                }
                            </select>
                            <a class="btn" id="btnEmailGroupsGo">Go <i class="fa fa-arrow-right"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-1"></div>
                </div>
               

                <!--Main Body!-->
                <div class="col-lg-12">
                    <div class="col-lg-2 pull-left"></div>
                    <div class="col-lg-8">
                        <!-- QUICK SMS Email Widget -->
                        <div class="col-lg-12">

                            <div>
                                <h3><i class="fa fa-envelope "></i> Quick Email</h3>
                            </div>
                            <div>
                                <div class="form-group">
                                    <input type="text" id="txtComposeEmailSubject" class="form-control" name="subject" placeholder="Subject" />
                                </div>
                                <div>
                                    <textarea class="textarea" id="txtAreaComposeEmailMessage" placeholder="Message" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>
                            </div>
                            <div class="clearfix pull-right">
                                <button class="pull-right btn btn-default" id="ComposeEmailSendEmail" style="border:none">Send <i class="fa fa-arrow-circle-right"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!--List Of Email Supposed-->
                <div class="col-lg-12">
                    <table id="composeEmailGrid" class="dataGrid table table-bordered table-striped  table-hover">
                        <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <td class="small-col"><input type="checkbox"/> Check All</td>
                                <th>First Name</th> 
                                <th>Middle Name</th>
                                <th>User Name</th>
                                <th>Role</th>
                                <th>Department</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>

        </section>
    </section>
</body>

SMSUI/Views/Announcement/Index.cshtml
@using SMSUI.Controllers
@using SMSUI.ViewModels.Announcement
@model IntranetAnnouncementInformationViewModel
@{
    Layout = ("~/Views/Shared/_LoggedInLayout.cshtml");
}

<body>
    <section id="main-content">
        <section class="wrapper">
            <div class="wizard-card" style="min-height: 300px; padding-left: 30px;padding-right: 20px">

                    <div>
                        <h3 class="centered" style="font-size: 40px; font-family: 'Calibri Light';"><i class="li_mail"></i> SMS <span style="font-size: 30px; font-family: 'Calibri Light';">Mail</span></h3>
                    </div>

                    <div class="row">
                        <div class="col-md-3 col-sm-4" style="margin-top: 15px;">

                            <!-- Compose Message -->
                            <div>
                                <a href="@Url.Action("ComposeMail","Announcement")" class="btn btn-block" style="border-color: transparent; color: black;"><i class="fa fa-pencil fa-2x" style="color: black; "></i> Compose</a>
                            </div>

                            <!-- Navigation - Mail-->
                            <div style="margin-top: 15px;">
                                <ul class="nav nav-pills nav-stacked">
                                    <li id="announcementInboxID"  style="background: #82E6F4; border-color: #82E6F4; border-radius: 5px; "><a style="background: transparent; color: black; border-color: #68dff0; border-radius: 5px;"><i class="fa fa-inbox"></i> Inbox (@Model.InBoxMails)</a></li>
                                    <li id="announcementSentID"><a style="background: transparent; color: black; border-color: #82e6f4; border-radius: 5px; "><i class=" fa fa-mail-forward"></i> Sent</a></li>
                                    <li><a href="#" style="color: black; border-color: #82E6F4;border-radius: 5px;"><i class="fa fa-pencil-square-o"></i> Drafts</a></li>
                                    <li><a href="#" style="color: black; border-color: #82E6F4; border-radius: 5px; "><i class="li_note"></i> Junk</a></li>
                                </ul>
                            </div>
                        </div>
                        <div id="divAnnouncementMailGrid">
                            @{
                                Html.RenderPartial("_Mail", Model.Announcements);
                            }
                        </div>
                    </div>

                </div>

        </section>
    </section>
</body>

SMSUI/Views/Announcement/MailDetail.cshtml
@using SMSUI.ViewModels.Announcement
@model MailDetailViewModel
@{
    Layout = ("~/Views/Shared/_LoggedInLayout.cshtml");
}

<section id="main-content">
    <section class="wrapper">

        <div class="wizard-card" style="min-height: 300px; padding-left: 30px;padding-right: 20px">
            <div><h3 class="centered" style="font-size: 40px; font-family: 'Calibri Light';"><i class="li_mail"></i> SMS <span style="font-size: 30px; font-family: 'Calibri Light';">Mail</span></h3></div>
            <div>
                <div>
                    <div class="row">
                        <div class="col-md-3 col-sm-4" style="margin-top: 15px;">
                            <!-- compose message btn -->
                            <div>
                                <a class="btn btn-block" style="border-color: transparent; color: black;"><i class="fa fa-pencil fa-2x" style="color: black; "></i> Compose</a>
                            </div>

                            <!-- Navigation - Mail-->
                            <div style="margin-top: 15px;">
                                <ul class="nav nav-pills nav-stacked">
                                    <li style="background: #82E6F4; border-color: #82E6F4; border-radius: 5px; "><a href="@Url.Action("Index","Announcement")" style="color: black; border-color: #68dff0; border-radius: 5px;"><i class="fa fa-inbox"></i> Inbox (@Model.InBoxMails)</a></li>
                                    <li><a onclick="SentMailFolderClicked()" style="color: black; border-color: #82E6F4; border-radius: 5px; "><i class="fa fa-mail-forward"></i> Sent</a></li>
                                    <li><a href="#" style="color: black; border-color: #82E6F4;border-radius: 5px;"><i class="fa fa-pencil-square-o"></i> Drafts</a></li>
                                    <li><a href="#" style="color: black; border-color: #82E6F4; border-radius: 5px; "><i class="li_note"></i> Junk</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-9 col-sm-8">
                            <!-- quick email widget -->
                            <div>
                                <div>
                                    <div class="form-group">
                                        <label>From :</label>
                                        <input type="email" class="form-control" style="font-family: 'Calibri Light'; font-size: 15px; line-height: 18px;" name="emailFrom" placeholder="Email From:" value="@Model.AnnouncementViewModel.From" />
                                    </div>                                   
                                     @if (Model.FakeSetting == "Sent")
                                    {
                                        <label>To :</label>
                                       <div class="form-group">
                                           <input type="text" class="form-control" style="font-family: 'Calibri Light'; font-size: 15px; line-height: 18px;" name="EmailTo" placeholder="To:" value="@Model.AnnouncementViewModel.To" />
                                        </div>
                                    }
                                    <div class="form-group">
                                        <label>Subject :</label>
                                        <input type="text" class="form-control" style="font-family: 'Calibri Light'; font-size: 15px; line-height: 18px;" name="subject" placeholder="Subject" value="@Model.AnnouncementViewModel.Subject" />
                                    </div>
                                    <div>
                                        <label>Message :</label>
                                        <textarea placeholder="Message" style="width: 100%; height: 125px; font-family: 'Calibri Light'; font-size: 15px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"> @Model.AnnouncementViewModel.Message</textarea>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clearfix">
                    <div class="pull-right">
                        <a href="@Url.Action("Index","Announcement")" class="btn" style="border:none"><i class="fa fa-arrow-circle-left"></i> Back</a>
                     </div>
                </div>
            </div>
        </div>
    </section>
</section>

SMSUI/Views/Announcement/_Mail.cshtml
@model List<SMSUI.ViewModels.Announcement.AnnouncementViewModel>
@{
    var context = (Model.Any(m => m.To != null) && Model.Any(m => m.To.Length > 1)) ? "Sent" : "Inbox";
}

<div class="col-md-9 col-sm-8">
    <div class="table-responsive table-hover">
        <!-- THE MESSAGES -->
        <label>Status</label>
        <table class="table">
            @foreach (var message in Model)
            {
                if (!message.IsSeen)
                {
                 <tr style="color: #424A5D;">
                    <td><i class="fa fa-star"></i></td>
                    <td>@message.From</td>
                    <td><a href="@Url.Action("MailDetail", new { @userAnnouncementID=message.AnnouncementID, context })" style="color: #424A5D;">@message.Subject</a></td>
                    <td>@message.Date</td>
                </tr>
                }
                else
                {
                <tr style="color: darkgrey;">
                    <td><i class="fa fa-star-o"></i></td>
                    <td>@message.From</td>
                    <td><a href="@Url.Action("MailDetail", new { @userAnnouncementID = message.AnnouncementID, context })" style="color: darkgrey;">@message.Subject</a></td>
                    <td>@message.Date<td>
                 </tr>
                }
            }
        </table>
    </div>
</div>
<div class="clearfix">
    <div class="pull-right">
        <small>Showing 1-@Model.Count</small>
        <button class="btn btn-xs" style="border-color: #82E6F4"><i class="fa fa-caret-left"></i></button>
        <button class="btn btn-xs" style="border-color: #82E6F4"><i class="fa fa-caret-right"></i></button>
    </div>
</div>